#!/bin/sh


function small() {
    if [[ ! -z $@ ]]; then
        if [[ $1 == "help" ]]; then
            echo "Here's the help"
        else
            for i in $@
            do
                if [[ ! -f $i ]]; then
                    touch $i
                fi
            done
            open -a "Syntra Small" $@
        fi
    else
        open -a "Syntra Small"
    fi
}